# Array 

In [2]:
import numpy as np

In [4]:
a=np.array([2,3,4])
a

array([2, 3, 4])

In [6]:
b=np.array([2,3,4,5,6,7]).reshape(2,3)
b

array([[2, 3, 4],
       [5, 6, 7]])

In [13]:
c=np.array([1,2,3,4,5,6,7,8,9,10,11,12]).reshape(2,2,3)
c

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [14]:
e = np.array([1, 2, 3, 4, 5, 6])
print(e.sum()) # Sum the array
print(e.min()) # Find the minimum value in an array
print(e.max()) # Find the maximum value in an array
print(e.mean()) # Find the arithmetic mean of an array

21
1
6
3.5


In [15]:
np.zeros(5) # Creates an array of zeros with 5 elements
np.linspace(0, 6, 10) # Creates an array of values from 0 through 6 in 10 even spaces
np.random.rand(3) # Three random values between 0 and 1
np.random.randint(1, 1000) # A random integer between 1 and 1000
np.arange(25) # Like the "Range" function we learned earlier, this is gives you a range of integers between 1 - 25


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [17]:
np.linspace(0, 6, 10)

array([0.        , 0.66666667, 1.33333333, 2.        , 2.66666667,
       3.33333333, 4.        , 4.66666667, 5.33333333, 6.        ])

In [22]:
np.random.rand(3)

array([0.08712945, 0.40202332, 0.95581921])

In [23]:
np.random.randint(1, 1000)

142